languageName: English
wieght: 2
contentDir: /content/en
description: "Andrzej @unjello Lichnerowicz"

params:
  tagline: he / him / activist / trees and greenery lover
  social:
    - name: linkedin
      url: https://www.linkedin.com/in/andrzejlichnerowicz/
    - name: twitter
      url: https://twitter.com/unjello
    - name: github
      url: https://github.com/unjello
    - name: blog
      url: /posts/
    - name: polywork
      url: http://poly.work/unjello
    - name: email
      url: mailto:andrzej@lichnerowicz.pl

  projects:
    header: projects
    desc: "This takes most of my free time."
    list:
      - name: One World-One Heart Foundation
        url: https://oneworld-oneheart.pl
        img: owoh.png
      - name: Polish Demoscene Chronicles
        url: https://kskpd.pl
        img: kskpd.png
      - name: Google Developers Group Cloud Kraków
        url: https://gdg.community.dev/gdg-cloud-krakow/
        img: gdg.png

  oss:
    header: oss
    desc: "I’ve written and contributed to lots of Open Source Software, including:"
    list:
      - name: safeshelter
        url: https://github.com/KoalicjaOtwartyKrakow
        desc: A backoffice system for Radziwiłłowska 3 Crisis Point.
      - name: org-mode
        url:  https://github.com/bzg/org-mode
        desc: A GNU Emacs major mode for convenient plain text markup — and much more.
      - name: foo_input_amr
        url:  https://github.com/unjello/foo_input_amr
        desc: amr-nb decoder for foobar2000
      - name: msctexen
        url:  https://github.com/unjello/msctexen
        desc: Mscgen in LaTeX
      - name: calkulator
        url:  https://github.com/unjello/calkulator
        desc: dos-navigator like, lightweight calculator for windows
      - name: pino-pretty-min
        url:  https://github.com/unjello/pino-pretty-min
        desc: minimalistic ndjson logger for pino

  talks:
    header: talks & workshops
    desc: "I often lead talks, workshops and classes around software engineering and demoscene:"
    list:
      - name: "Polish Demoscene: UNESCO Intangible Cultural Heritage"
        url: https://www.pixelheavenfest.com/program/
        where: Pixel Heaven Games Festival, Warszawa
        year: 2022
        type: Panel
      - name: "Keynote"
        url: https://gdg.community.dev/events/details/google-gdg-cloud-krakow-presents-devfest-polska-2021/
        where: DevFest Polska, Kraków
        year: 2021
        type: Keynote
      - name: "Art of limits and randomness"
        url: https://digitaldragons.pl/programme/speakers/andrzej-lichnerowicz/
        where: Digital Dragons, Kraków
        year: 2021
        type: Lecture
      - name: "DEMOSCENA ⨉ UNESCO. Quo Vadis?"
        url: https://xenium.rocks/en/events
        where: Xenium Festival, Katowice
        year: 2021
        type: Lecture
      - name: "Q&A: Workshop: Limitations Driven Creativity Through Demoscene Lenses (Session Chair)"
        url: https://s2021.siggraph.org/session/?sess=sess242
        where: SIGGRAPH
        year: 2021
        type: Live Session
      - name: "Workshop: Limitations Driven Creativity Through Demoscene Lenses (Organizer)"
        url: https://s2021.siggraph.org/presentation/?id=fwkp_103&sess=sess242
        where: SIGGRAPH
        year: 2021
        type: Workshop
      - name: "Demoscene in UNESCO - interview with Unjello (Polish)"
        url: https://www.youtube.com/watch?v=mYfE5odcwk8
        where: Lata 90 Podcast Retro
        year: 2021
        type: Inteview
      - name: Your own virtual camera — or neural networks for everyone (Polish)
        url: https://www.facebook.com/events/265684168587664/?post_id=274603347695746&view=permalink
        where: mAIówka z WRSS, Kraków
        year: 2021
        type: Workshop
      - name: Do different age groups have different needs? Oxford debate.
        where: Sabre Polska, Kraków
        year: 2021
        type: Oxford Debate
      - name: Future of travel — how AI is changing travel industry (Polish)
        url: https://www.youtube.com/watch?v=6IdPNdw9fIo
        where: CEREBRO, Kraków
        year: 2021
        type: Talk
      - name: Demoscene for UNESCO intangible cultural heritage
        url: https://www.youtube.com/watch?v=UDLfaFZYoJ4&t=1s
        where: Revision
        year: 2021
        type: Panel
      - name: "Podcast Episode #107 — Demoscene: The Art of Coding"
        url: https://sceneworld.org/blog/2021/02/16/podcast-episode-107-demoscene-the-art-of-coding/
        where: Scene World
        year: 2021
        type: Panel
      - name: Test-Driven Development Dojo
        where: KNII Cracow University of Technology
        year: 2019
      - name: Test Driven Development
        where: Case Week, Silesian University of Technology
        year: 2019
  works:
    header: art
    desc: "Below are a few passion projects:"