languageName: English
wieght: 1
contentDir: /content/en
description: "Andrzej @unjello Lichnerowicz"

params:
  tagline: leader? / follower / bitwise operator / demoscener / activist / trees and greenery lover
  social:
    - name: foundation
      url: https://oneworld-oneheart.pl
    - name: committee
      url: https://kskpd.pl/en
    - name: twitter
      url: https://twitter.com/unjello
    - name: instagram
      url: http://instagram.com/unje11o
    - name: polywork
      url: http://poly.work/unjello
#    - name: blog
#      url: http://andrzej.lichnerowicz.pl/posts/
    - name: github
      url: https://github.com/unjello
    - name: shadertoy
      url: https://www.shadertoy.com/user/unjello
    - name: linkedin
      url: https://www.linkedin.com/in/andrzejlichnerowicz/
    - name: facebook
      url: https://www.facebook.com/andrzej.lichnerowicz
    - name: tiktok
      url: https://tiktok.com/@unjello
    - name: email
      url: mailto:andrzej@lichnerowicz.pl

  oss:
    header: oss
    desc: "I’ve written and contributed to lots of Open Source Software, inculding:"
    list:
      - name: org-mode
        url:  https://github.com/bzg/org-mode
        desc: A GNU Emacs major mode for convenient plain text markup — and much more.
      - name: foo_input_amr
        url:  https://github.com/unjello/foo_input_amr
        desc: amr-nb decoder for foobar2000
      - name: msctexen
        url:  https://github.com/unjello/msctexen
        desc: Mscgen in LaTeX
      - name: calkulator
        url:  https://github.com/unjello/calkulator
        desc: dos-navigator like, lightweight calculator for windows
      - name: pino-pretty-min
        url:  https://github.com/unjello/pino-pretty-min
        desc: minimalistic ndjson logger for pino

  talks:
    header: talks & workshops
    desc: "I often lead talks, workshops and classes around software engineering and demoscene:"
    list:
      - name: Your own virtual camera — or neural networks for everyone (Polish)
        url: https://www.facebook.com/events/265684168587664/?post_id=274603347695746&view=permalink
        where: mAIówka z WRSS, Kraków
        year: 2021
        type: Workshop
      - name: Future of travel — how AI is changing travel industry (Polish)
        url: https://www.youtube.com/watch?v=6IdPNdw9fIo
        where: CEREBRO, Kraków
        year: 2021
        type: Talk
      - name: Demoscene for UNESCO intangible cultural heritage
        url: https://www.youtube.com/watch?v=UDLfaFZYoJ4&t=1s
        where: Revision
        year: 2021
        type: Panel
      - name: "Podcast Episode #107 — Demoscene: The Art of Coding"
        url: https://sceneworld.org/blog/2021/02/16/podcast-episode-107-demoscene-the-art-of-coding/
        where: Scene World
        year: 2021
        type: Panel
      - name: Test-Driven Development Dojo
        where: KNII Cracow University of Technology
        year: 2019
      - name: Test Driven Development
        where: Case Week, Silesian University of Technology
        year: 2019