baseURL: https://andrzej.lichnerowicz.pl/
languageCode: en_US
defaultContentLanguage: en
theme: hugo-andrzej-theme
title: "@unjello"

params:
  author: Andrzej Lichnerowicz <andrzej@lichnerowicz.pl>
  keywords: demoscene, demoscena
  thumbnail: https://andrzej.lichnerowicz.pl/images/card.jpg
  url: https://andrzej.lichnerowicz.pl/
  fb_app_id: 821195935327934
  twitter_id: "@unjello"
  header: Andrzej unjello Lichnerowicz

  socialmedia:
    email: "kontakt@kskpd.pl"
    tiktok: https://www.tiktok.com/@kronikapolskiejdemosceny
    twitter: https://twitter.com/kronikaplsceny
    instagram: https://www.instagram.com/kronikapolskiejdemosceny/
    facebook: https://www.facebook.com/kronikapolskiejdemosceny
    github: https://github.com/Kronika-Polskiej-Demosceny
    linkedin: https://www.linkedin.com/company/komitet-spo%C5%82eczny-kronika-polskiej-demosceny/
    youtube: https://www.youtube.com/channel/UCbr4KVNuW9AcIFk3HRPLQJQ