baseurl = "http://andrzej.lichnerowicz.pl"
DefaultContentLanguage = "en"
title = "andrzej lichnerowicz"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsUseClasses = true
pygmentCodeFences = true
disqusShortname = "yet-another-home-page"
googleAnalytics = "UA-19850879-1"
contentDir = "content"
defaultLayout = "post"
enableRobotsTXT = "true"
publishDir = "docs"

[Params]
  subtitle = "yet another home page"
  logo = "img/avatar.jpg"
  favicon = "img/favicon.ico"
  commit = false
  rss = true
  comments = true


[Author]
  name = "Andrzej Lichnerowicz"
  website = "http://andrzej.lichnerowicz.pl"
  #email = "user@host.com"
  #facebook = "username"
  #googleplus = "107600132340306253060" # or xxxxxxxxxxxxxxxxxxxxx
  github = "unjello"
  #gitlab = "unjello"
  twitter = "unjello"
  #reddit = "unjello"
  linkedin = "andrzejlichnerowicz"
  #xing = "username"
  #stackoverflow = "users/526604/andrzej-lichnerowicz"
  #snapchat = "username"
  #instagram = "username"
  #youtube = "user/username" # or channel/channelname
  #soundcloud = "username"
  #spotify = "username"
  #bandcamp = "username"
  #itchio = "username"
  #vk = "username"
  #paypal = "username"
  #telegram = "username"

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 3
